### ISSUE TITLE
openstack_security group should not list Non-VPC RFC-1918 CIDR error

### ISSUE THREAD

**Issue by naggappan** [Netflix/security_monkey#1039]
Openstack environment do not have a VPC so while listing securit group issues it should not give the following error,

"Non-VPC Security Group contains Private RFC-11918 CIDR" issue as this issue is applicable only to AWS environment. Attached screen shot of error type.

![image](https://user-images.githubusercontent.com/6483592/38813183-eec9797e-41ab-11e8-9cca-c5a871744dbe.png)

**Comment by mikegrima** [comment]
This is because the OpenStack security group auditor is subclassing the AWS Security Group auditor.
https://github.com/Netflix/security_monkey/blob/develop/security_monkey/auditors/openstack/openstack_security_group.py#L26

You'll need to either re-implement or override the AWS specific methods.

I think it would be worthwhile to make a generic auditor for network and have subclass the AWS, GCP, and OpenStack auditors against it with cloud-specific auditor functions.

**Comment by naggappan** [comment]
@mikegrima  I am able to override the AWS specific function just by adding the below in openstack/openstack_security_group.py

````
def check_securitygroup_ec2_rfc1918(self,sg_item)
````

When I do this it is ignoring the RFC errors and fixies the issue.

Now thinking the 2nd way gneric auditor for network and subclass, I am not sure what exactly you are trying to say here. Can you please elobrate or specify a draft like how it can be implemented ?

**Comment by mstair** [comment]
@naggappan I added the rfc1918 override to #1066.

**Comment by mikegrima** [comment]
This has been fixed in #1066.
