### ISSUE TITLE
Pluggable rulesets in security monkey

### ISSUE THREAD

**Issue by echiu64** [Netflix/security_monkey#157]
We need a way to better extend and manage security monkey, especially for more "opinionated" rules that don't necessarily belong in the core (or maybe all rules should move outside of core?)

Initial idea:
- Add pluggable rules to each service module (s3, iam, elb, etc)
  - Rules to be defined using JSON and json-path type queries
- Add pre/post module hooks
  - e.g. filter out non attached "risky" IAM policies

Future:
- move all rules into this format?

**Comment by monkeysecurity** [comment]
+1!!

**Comment by monkeysecurity** [comment]
There are a few ways to go about this.

## To disable current rules (like the opinionated ones):
- Currently, there is an "Auditor Settings" tab in securitymonkey where you can disable a given rule for a given account.  This currently prevents those issues from showing up in the issues search page, though they still appear in the Item details.  This isn't exactly what you're requesting, but it is in the same space.

- We could also assign an ID to each rule, and in the config file we could provide a set of disabled rules.  We could also extend the Web UI to enable/disable a rule globally.  This would be similar to the Auditor Settings, but taken a little further.

- I'd love to hear which rules you feel are overly opinionated.  Let's put a few in the gitter.im chat.  Maybe we'll remove a few entirely.

## To add new rules that you don't wish to commit back:
- We could do something similar to what iSecPartners has done with Scout2, https://isecpartners.github.io/Scout2/ See the section at the bottom on "How to create a new rule".
- They have you update json, add a python method, and update the report HTML.


- We could probably streamline our implementation so that there would be no need to update JSON or muck around in HTML.  You would just create a method with a name starting with check_* and place it in a file in the new pluggable folder.  ```security_monkey/pluggable/s3.py```

We'd update the .gitignore to ignore everything in pluggable.
The regular ```s3.py``` would attempt to import from ```security_monkey/pluggable/s3.py``` if it exists, and if so, do a dir() on the module and execute any methods beginning with check_*.

So @echiu64, let me know what you think of some of these ideas.  Which ones would add value for you?

**Comment by echiu64** [comment]
Oh i didn't mean to say the current ruleset was opinionated. I wanted to add in some rules that I feel may be overly opinionated or others may find opinionated?

@monkeysecurity I like all these ideas... I haven't looked at the code too deeply, honestly looking for the path of least resistance, so any pointers you have would be great and I can hopefully start working on it. The one thing I'd suggest is to target say 80% of the rules could be done using just json-path expressions which will make it easier for those that don't want to code any python?

**Comment by echiu64** [comment]
@monkeysecurity After marinating for a bit, here are my thoughts.

Have ```pluggable/[monitor]``` directories, such as ```pluggable/s3``` and then for each ```.py``` file in that directory (or recursive, depth 1), we would run methods starting with ```check_```

This allows me to pull in other rules in rather than merge into a single file.

e.g.
```pluggable/s3/logging.py``` and ```pluggable/s3/lifecycle.py```

For existing rules in "core", maybe we then run all methods that start with ```post_``` in the pluggable directory as well?

e.g. If I wanted to remove any audit issues on IAM for managed policies that have 0 attach count, I could write a ```post_remove_unattached_policies``` method and place it in ```pluggable/policy/unattached.py```

**Comment by monkeysecurity** [comment]
Linking to #231 and #297 so I can close those as duplicates.

**Comment by devlinrcg** [comment]
+1 on this.

**Comment by monkeysecurity** [comment]
I started playing with this idea a little bit.

https://github.com/monkeysecurity/cloudaudit/blob/support_config_rules/cloudaudit/aws/iam/iam_user.py

It's an extremely early work in progress, but the idea is to have rules that will work with AWS Config Rules, or security_monkey, or any other app (I'd love to work with Scout2 as well.)

Each issue has an `_id` so we can change the text of the issue without losing justifications, or disable the check from within the security_monkey UI, even after it has been imported into python.  Each  check will have a default_score, which implies the app using the library is capable to provide the ability to override this score.

Each check should define which fields it is using, and these fields should work with the cloudaux library.  So if you wanted to script up a check to pull all IAM Users, but only check for access keys, you could build a set of needed fields and only pull those.  (No need to pull user policies if you're only checking access keys.)

**Comment by monkeysecurity** [comment]
Custom auditors was implemented in #410.  I will continue work to break out audit issues into a separate library.
