### ISSUE TITLE
 ERROR: remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by brian-olson** [Netflix/security_monkey#185]
I added approximately 20 AWS accounts to a functional SM instance. Upon enabling all accounts and rebooting I'm getting the error message below. As best I can tell there is a limitation on the connection count from SM. 

== Error from Log file == 
OperationalError: (OperationalError) FATAL:  remaining connection slots are reserved for non-replication superuser connections
===================

So I modified these lines in the config in an attempt to resolve the problem:

===================
SQLALCHEMY_POOL_SIZE = 100
SQLALCHEMY_MAX_OVERFLOW = 30
===================

But no change in the error. The psql backend is a t2.small AWS RDS node. 

Any idea where the issue is here?

Thanks!

**Comment by monkeysecurity** [comment]
Any idea how long it runs before you get this error?  If you have some time, I'd be interested to know if it goes away (or hides a bit longer) when you upgrade the RDS instance size.

Did you clone from the master branch or the develop branch?

Does the supervisor properly restart everything when this happens?

Thanks for the report.

**Comment by brian-olson** [comment]
Hey Patrick,

Our instance had been running for a few days. I didn't notice that a NAT
box failed and there was no longer any external connectivity. Once this was
fixed and everything was rebooted all issues were resolved. I'm thinking
this was the cause of the problem.

During the time of the issue everything looked to be up and running. No
failures in supervisor or in the log files. Eventually the logs would show
a timeout, but I was thinking timeout as far as the backend db not a
failure to connect to the aws api's.

Thanks!

Brian

**Comment by moritzheiber** [comment]
The problem is pretty easy to mitigate. Amazon uses an instances' available memory for calculating the value of `max_connections` in the default parameters assigned to your RDS instance.

The available memory for a t2.small instance on RDS is 2GB. The calculation is `DBInstanceClassMemory/31457280`.

`2147483648 / 31457280 = 68,26` (i.e. 68)

If you exceed this value (maybe through multiple servers running behind a load balancer), your database's connection limit will be reached and you will get the error message mentioned above. Just raise the `max_connection` limit by creating a separate parameter group (don't modify the defaults) and assigning it to your instance. You can do so without having to restart it. A sane value for pretty much any micro/small level RDS node is anything below 500 (from experience).

**Comment by monkeysecurity** [comment]
Dang @moritzheiber - good description and fix.
