### ISSUE TITLE
SMTPException: SMTP AUTH extension not supported by server.

### ISSUE THREAD

**Issue by vishnudxb** [Netflix/security_monkey#225]
I used the SMTP instead of SES. 

EMAILS_USE_SMTP = True     # Otherwise, Use SES
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 587
MAIL_USE_SSL = True
MAIL_USERNAME = 'username'
MAIL_PASSWORD = 'password'

The smtp is working fine, I had tested it. However when I used to send the alerts via SMTP in security monkey, it gives this error.

![maill](https://cloud.githubusercontent.com/assets/4784716/10394851/0f319346-6e9a-11e5-9481-9885b84fb5a6.png)

**Comment by monkeysecurity** [comment]
Could you set MAIL_USE_SSL to True and let me know if that works?

**Comment by vishnudxb** [comment]
I am using MAIL_USE_SSL = True

**Comment by monkeysecurity** [comment]
Assuming from the original description that you are using gmail.

I wonder if you need to enable POP/IMAP for your gmail account in order to use SMTP.  Could you check if you have one of those enabled?

The gmail instructions identify the following information for SMTP:
https://support.google.com/mail/troubleshooter/1668960?hl=en&rd=1#ts=1665018%2C1665144

Outgoing Mail (SMTP) Server - Requires TLS
smtp.gmail.com
Port: 465 or 587
Requires SSL: Yes
Requires authentication: Yes
Email address: your full Gmail address (username@gmail.com) Google Apps users, please enter username@your_domain.com
Password: your Gmail password

If you have MFA enabled on your account, you may need to grab an "App password" and use that instead:
https://myaccount.google.com/security?utm_source=OGB#signin

Could you let me know if any of this helps?

**Comment by vishnudxb** [comment]
@monkeysecurity  As I said before, SMTP was working fine, I tested it. Even I tried it with MAIL_USE_SSL with True and False.  Also I tried it with TLS.  Couldn't get time to check it afterwards, will check it again and will post the update here.
Thanks

**Comment by vishnudxb** [comment]
@monkeysecurity  closing this, I make it work with SSL True, there was an issue with my SSL connection and after fixing that, everything works fine.
Thanks for the support.
