### ISSUE TITLE
ImportError: cannot import name send_email

### ISSUE THREAD

**Issue by oba11** [Netflix/security_monkey#232]
While trying to run manage db upgrade, go the error `ImportError: cannot import name send_email`.
Stack trace below.

```
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    from security_monkey import app, db
  File "/opt/secmonkey/security_monkey/__init__.py", line 96, in <module>
    from security_monkey.common.utils import send_email as common_send_email
ImportError: cannot import name send_email
```

Not sure if I'm missing anything.
Thanks.

**Comment by brian-olson** [comment]
I had this same problem yesterday. The solution was to follow the instuctions outlined here: https://github.com/Netflix/security_monkey/issues/205

AFAIK the key is to start with a fresh git clone and then just copy over your env-config/config-deploy.py file. Make sure you keep a backup of the entire directory until you get it working :)

**Comment by mikegrima** [comment]
I also experienced this issue the other day as well.

As @brian-olson mentioned, I resolved it by doing a fresh git clone (actually did a fresh fork and clone).

**Comment by monkeysecurity** [comment]
If any python folks can explain to me how I caused this, I'd love to learn what I did wrong and avoid the issue in the future.

The only thing I can think of is that when I refactored `securitymonkey.common.utils.utils` into `securitymonkey.common.utils`, maybe the .pyc files remained and confused the interpreter.  I never ran into the issue on my development box, nor in production, and neither did another colleague, but @mikegrima did see it.  I suspect we didn't have an issue in production because of our immutable instance deployment.

**Comment by brian-olson** [comment]
When I originally attempted to fix the existing installation I did a diff
on this file and saw that chance. So I changed securitymonkey.common.utils back
to securitymonkey.common.utils.utils, but that just caused more errors. I
didn't want to get started down that road so I just made a fresh clone. So
you may be correct that something was lingering.
