### ISSUE TITLE
Multi-Factor Authentication

### ISSUE THREAD

**Issue by Mr19** [Netflix/security_monkey#306]

**Comment by monkeysecurity** [comment]
security_monkey currently relies on flask-security which does not support mfa.

They've had an open issue on it since Dec 2014:
https://github.com/mattupstate/flask-security/issues/350

We're in the very early stages of a rewrite that will plug into your company's SSO like Onelogin or Okta or Ping, but still have an optional local username/password for backup.

So, I think we'll have this feature via the SSO.

**Comment by monkeysecurity** [comment]
The SSO PR (#354) has been merged to develop.  That's our MFA solution.

I left a comment on the flask-security feature request, but the feature does not seem like it is one of their priorities.

**Comment by Mr19** [comment]
Perfect, Thanks for the update.
