### ISSUE TITLE
Security Monkey outside AWS

### ISSUE THREAD

**Issue by subbu05** [Netflix/security_monkey#366]
Hi,

We wanted to have Security Monkey installed outside AWS for security reasons.
Can we use access key based instead role based access? Any idea what files to be changed?

**Comment by mikegrima** [comment]
Hi @subbu05 

For security reasons, you would want to run Security Monkey within AWS so that you can take advantage of IAM roles and on-instance credentials.  Launching a instance with an IAM role automatically provides credentials to your application without having to keep, store, and manually rotate IAM access keys.  The management of IAM static keys have significant security implications, which are avoided by using on-instance credentials with IAM roles.

The above being said, Security Monkey utilizes Boto.  As long as you set up your environment so that Boto can obtain the correct credentials, it should be OK.  However, as a note of caution, this is not the recommended way to run Security Monkey.  

We do provide some documentation for this type of use case with regards to running Security Monkey within a Docker container.  You can find documentation on that here: https://github.com/Netflix-Skunkworks/zerotodocker/wiki/Security-Monkey

Thank You
