### ISSUE TITLE
Productionalizing Security Monkey - SES Documentation

### ISSUE THREAD

**Issue by JaguarSecurity** [Netflix/security_monkey#50]
Every one has been very helpful so far but I would use a little help in the documentation for setting up SES and more information under the Productionalizing Security Monkey section. Thanks!

**Comment by LazyGetter** [comment]
The above link seems to be broken. Is there any other place where I can find instructions to setup email ?

**Comment by monkeysecurity** [comment]
Hey @LazyGetter 

The file was renamed from quickstart1.html to just quickstart.html:
http://securitymonkey.readthedocs.io/en/latest/quickstart.html#productionalizing-security-monkey

Security Monkey uses a package called Flask-Mail to send email.  It handles both smtp, and ses using boto.

AWS has their own instructions for enabling SES.  You can even setup SES to use SMTP instead of IAM credentials, though I prefer IAM.

**Comment by Divya9n** [comment]
Members here are very keen to help and have resolved most of the errors I get after going through various comments here. We have set up security monkey and want to check the email service to receive the reports.
Where can I find detailed instruction on setting up SES as the quick start document does not have details with snapshots as for the other steps.

Thanks in advance

**Comment by monkeysecurity** [comment]
Probably one of the two "Email Sending" tutorials available here:

https://aws.amazon.com/ses/getting-started/
