### ISSUE TITLE
SECURITY_TRACKABLE seems broken with SSO

### ISSUE THREAD

**Issue by cstewart87** [Netflix/security_monkey#501]
The Users settings page does not display any data (besides email) for users that have authenticated with Ping SSO.  "Login Count" is always 0, and all other fields are empty.

**Comment by monkeysecurity** [comment]
I noticed this as well.

I thought it was because previou versions used:

`from flask_login import login_user`

so I recently changed it to this:

`from flask_security.utils import login_user`

https://github.com/Netflix/security_monkey/blob/develop/security_monkey/sso/views.py#L16

However, it does not seem to have fixed it.

I'm not exactly sure why, as the method we're now calling looks like it should be doing the SECURITY_TRACKABLE things:

https://github.com/inveniosoftware/flask-security-fork/blob/master/flask_security/utils.py#L54

I think it'll require some debugging.
