### ISSUE TITLE
Plugins support

### ISSUE THREAD

**Issue by redixin** [Netflix/security_monkey#503]
Currently it is not possible to add new account types, watchers, auditors without forking and adding new ones to ``*/custom/`` directory.

To make any custom class available it's enough to import module containing custom subclass. There are two simple ways to do this:

1. Add config option ``IMPORT_MODULES`` with list of strings to import by importlib.import_module

2. Use ``entry_points``. E.g. import all modules listed by plg_resources.iter_entry_points("security_monkey_plugins")

First way is a bit more safe and flexible.

I'm ready to implement any of this or maybe other one if you have any suggestions.

**Comment by mariusgrigaitis** [comment]
I'm currently facing the same problem of needing to modify source code in security_monkey to add additional auditors.

Would like the first way.

**Comment by monkeysecurity** [comment]
Hey @kevgliss and @mikegrima - thoughts?

**Comment by kevgliss** [comment]
I believe the second way is generally the more accepted way of accomplishing this. Because `entry_points` is supported by disutils, plugins can totally outside of the security monkey source code. Adding new watchers/auditors would be as easy as simply installing an additional package. 

As an example in [Lemur](https://github.com/Netflix/lemur) we use `entry_points` for both first-party as well as third-party plugins. We keep plugins that we maintain in the Lemur's repository while allowing others to host their owner plugins elsewhere. Since they end up as actual python packages they can also be shared and distributed via `pipy`. 

Additionally, we have several internal-only plugins that are packaged and installed as needed when we deploy. In this way, `Security Monkey` users would be able to customise their install just by editing their `setup.py`. 

More advanced support could then also be built to allow configuration/enablement from the UI, API, etc. 

There are several libraries ([Yapsy](http://yapsy.sourceforge.net/)) you could use to accomplish this, but it also fairly easy to implement yourself due to python's dynamic nature. [Here's](https://github.com/Netflix/lemur/blob/master/lemur/plugins/bases/destination.py) an abstract object that a plugin would have to implement. If you were to define a `watcher` base object it abstracts quite a bit of complexity away from those who just want to watch a new resource. 

More examples:
[Installing the plugin](https://github.com/Netflix/lemur/blob/master/lemur/factory.py#L159)
[Regstration](https://github.com/Netflix/lemur/blob/master/lemur/plugins/base/manager.py#L54)
[Getting a registered plugin](https://github.com/Netflix/lemur/blob/master/lemur/plugins/base/manager.py#L30)

**Comment by redixin** [comment]
Thank you for links! I'll check them out and start my work.
