### ISSUE TITLE
AssumeRole operation not permitted when using cross-account roles.

### ISSUE THREAD

**Issue by LazyGetter** [Netflix/security_monkey#530]
I am trying to manage multiple accounts via the same securityMonkey instance. I have followed all steps to setup SecurityMonkey role in the "other" account (the one not running the sec monkey server) and added the trust relationship with the "original" account id, allowing it to do assumeRole.

In the "original" account, I updated the SecurityMonkeyLaunchPerms policy as below 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ses:SendEmail"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "*"
        }
    ]
}
```

However, I still get the below error in the log when i do an update using
      `python manage.py find_changes -a <name>`

`(AccessDenied) when calling the AssumeRole operation: Not authorized to perform sts:AssumeRole' [in /usr/local/src/security_monkey/security_monkey/watcher.py:172]`

Same exception almost everywhere. I have looked at a similar issue opened earlier and followed the steps. But still the same error. Is there something else that could be missing ?

**Comment by monkeysecurity** [comment]
http://securitymonkey.readthedocs.io/en/latest/quickstart.html#setup-iam-roles

So the ability to assumerole needs to be setup in two places:
1) The `SecurityMonkeyInstanceProfile` must have a policy allowing it.  Your statement above should suffice, though I feel it would be better to limit the resource to something like this if possible: `"arn:aws:iam::*:role/SecurityMonkey"`
2) The role that is being assumed into must have a trust policy allowing the original role to assume into it.  Here is a sample trust policy:

```
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::<YOUR ACCOUNTID GOES HERE>:role/SecurityMonkeyInstanceProfile"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

Note: The trust policy goes in a different place than the inline policies.

If you have those two, then it should work.  If it still does not work, I would look for any DENY statements that you may have attached as either an inline policy or as a managed policy.  If you're using an IAM USER instead of an IAM ROLE, check for any DENY statements in any IAM Groups the USER is a member of.
