### ISSUE TITLE
S3 pagination marker failing. Should use ContinuationToken instead of NextContinuationToken

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/security_monkey#550]
The s3 watcher is failing on a bucket with a lot of metadata.

Error:
Parameter validation failed:
Unknown parameter in input: "NextContinuationToken", must be one of: Bucket, ContinuationToken'

Probably a cloudaux issue. 
https://github.com/Netflix-Skunkworks/cloudaux/search?utf8=%E2%9C%93&q=NextContinuationToken

I wonder if AWS changed the name of their pagination marker for AnalyticsConfigurationList or MetricsConfigurationList or if we've had it wrong since adding analytics/metrics support.

**Comment by mikegrima** [comment]
It looks like the issue is that the S3 API uses both --
When requesting a new page, you need to send over `ContinuationToken`. In the response from AWS, there will be a `NextContinuationToken` for the next page in the results.

This appears to be newer behavior as other AWS services just use `Marker` that changes along with each request. CloudAux's pagination logic will need to be updated to reflect differing Request/Response pagination markers.

**Comment by mikegrima** [comment]
Addressed in: https://github.com/Netflix-Skunkworks/cloudaux/pull/18

**Comment by mikegrima** [comment]
Merged CloudAux PR. Submitting new PR to SM to up CloudAux dependency to `>=1.1.1`.

**Comment by mikegrima** [comment]
Addressed in #560
