### ISSUE TITLE
security_monkey is support China AWS of BJS ??

### ISSUE THREAD

**Issue by BenRuan** [Netflix/security_monkey#699]
security_monkey is support China AWS of BJS ??

**Comment by monkeysecurity** [comment]
Security Monkey will try to slurp from all regions.

I don't have access to `cn-north-1` or to the US Govcloud regions, so I have not tested it on them.

Older watchers ignore exceptions from "trouble regions":
https://github.com/Netflix/security_monkey/search?utf8=%E2%9C%93&q=trouble+regions&type=

Newer watchers should record the exception in the database table and move on.

So, I can't be sure if the China regions will work, but I'd love to find out.

**Comment by BenRuan** [comment]
@ @I have installed a security monkey, but the web UI interface is anonymous landing, and the error message is the API call failed 503 gateway error, I very much hope that we can solve this problem, thank you very much for your reply. BTW，arn:aws-cn:(AWS account): role / SecurityMonkeyInstanceProfile, https: // (AWS account) .signin.amazonaws.cn / console, but abroad is a completely different ARN @ @

**Comment by BenRuan** [comment]
@monkeysecurity @ @I have installed a security monkey, but the web UI interface is anonymous landing, and the error message is the API call failed 503 gateway error, I very much hope that we can solve this problem, thank you very much for your reply. BTW，arn:aws-cn:(AWS account): role / SecurityMonkeyInstanceProfile, https: // (AWS account) .signin.amazonaws.cn / console, but abroad is a completely different ARN @ @

**Comment by monkeysecurity** [comment]
Oh the ARNs contain `aws-cn` instead of just `aws`.  That's going to break a few things like the regex in the ARN class.

Your 503 error: 
That could happen if there are no healthy instances behind the ELB, OR if gunicorn is not running.

    sudo supervisorctl status

I presume it will say that `securitymonkey` is not running.

You could try manually starting the python server:

    monkey run_api_server

And see if it starts up or errors out.

**Comment by BenRuan** [comment]
@monkeysecurity                  Error 503 gateway has been resolved, but the new problem again, I am in the security monkey web 'interface Create Account  Add AWS account, China AWS is no Canonical ID meaning, only one account ID, add AWS account is not enough to save, the problem is quite trouble, ha ha,
2029-04-27 04:13:26 UTC LOG: could not receive data from client: Connection reset by peer
2022-04-27 04:13:26 UTC LOG: unexpected EOF on client connection with an open transaction

**Comment by monkeysecurity** [comment]
Canonical ID explained here:

http://docs.aws.amazon.com/general/latest/gr/acct-identifiers.html

It's the replacement for the "s3 name" since AWS is deprecating the s3 name.

I believe you can put a dummy value in for the canonical ID and then run:

    monkey fetch_aws_canonical_ids

You can also add an account from the CLI:

https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md#add-your-awsgcp-accounts

```
usage: manage.py add_account_aws [-h] -n NAME [--thirdparty] [--active]
                             [--notes NOTES] --id IDENTIFIER
                             [--update-existing]
                             [--canonical_id CANONICAL_ID]
                             [--s3_name S3_NAME] [--role_name ROLE_NAME]
```
