### ISSUE TITLE
REST API for SM

### ISSUE THREAD

**Issue by shreyasmrs** [Netflix/security_monkey#717]
Is there any REST API exposed to control SM, if yes where can I get the docs for it.

Thanks
Shreyas

**Comment by monkeysecurity** [comment]
duplicate of #596 

There is a REST API, however it currently requires a session cookie for authentication instead of a more common API token other apps use (like a header/bearer token/jwt token)

long term plan is to replace `flask security` and add in JWT tokens for easier API access.

Best documentation for this is in the code right now:
https://github.com/Netflix/security_monkey/blob/develop/security_monkey/views/item.py#L37

Poke through the files in that `views` folder.

The web app uses the API to load all the info, so it's probably easiest to just open the inspector in Chrome and watch the network calls.
