### ISSUE TITLE
Monkey command does not run

### ISSUE THREAD

**Issue by devonartis** [Netflix/security_monkey#768]
I setup Security monkey on AWS ... I went through the full quickstart quide. But when I try to run the command "monkey db upgrade" there is no command called monkey.

Has anyone seen this problem before ...

**Comment by mikegrima** [comment]
Are you in the `venv`?

**Comment by devonartis** [comment]
No I am not in venv ....

**Comment by devonartis** [comment]
So I have to run it always in virtualenv ...

**Comment by devonartis** [comment]
@mikegrima  thanks for your feedback

**Comment by devonartis** [comment]
I will try venv ...

**Comment by mikegrima** [comment]
All security monkey commands **must** be run within the `venv`.

**Comment by devonartis** [comment]
@mikegrima thanks that worked ...

**Comment by Leectan** [comment]
I have the same issue even issue "monkey db upgrade" in venv environment. any help is appreciated.

**Comment by mikegrima** [comment]
@Leectan Did you perform your pip installs from within the venv?

**Comment by Leectan** [comment]
mike, thanks for the unexpected quick response.
yes I did, I've tried to run ALL the pip install commands all over again and now I have this error message.
<img width="1256" alt="screen shot 2018-03-06 at 12 34 59 pm" src="https://user-images.githubusercontent.com/24819052/37048154-08a6b550-213b-11e8-9ac0-fe025db4650b.png">

**Comment by mikegrima** [comment]
That says that it can't find the config file at `/usr/local/src/security_monkey/env-config/config-deploy.py`.

You need to have the `SECURITY_MONKEY_SETTINGS` environment variable point to the location that your configuration is.

**Comment by Leectan** [comment]
Thanks, I went and config the setting in the config-deploy.py file to point to the AWS DNS name per Quickstart guide and I got this error?
<img width="1370" alt="1" src="https://user-images.githubusercontent.com/24819052/37053261-a259f15e-2149-11e8-9f63-a6f5cd25d43b.png">

**Comment by mikegrima** [comment]
You're in the wrong directory.

I would suggest reviewing: https://github.com/Netflix/security_monkey/blob/develop/docs/installation/03-install-sm.md

**Comment by Leectan** [comment]
Thanks mike, I re-configure the whole process and seems like everything is working well until this part. I've made sure along the way that nginx is working through https and port 443 is open for it in SG. This part seemed to be the part holding me up.
<img width="1327" alt="screen shot 2018-03-07 at 11 10 18 pm" src="https://user-images.githubusercontent.com/24819052/37132740-698667da-225d-11e8-8c20-04e00e321536.png">
<img width="747" alt="2" src="https://user-images.githubusercontent.com/24819052/37132751-707e7af0-225d-11e8-96e1-061b386df6be.png">
Any idea what I'm missing here??? google doesn't seem to know this issue here.

**Comment by mikegrima** [comment]
Check that you can curl the localhost on 443 on the instance. If you can, then verify that the security group configuration is correct to ingress your source IP.

**Comment by Leectan** [comment]
mike, thanks
<img width="933" alt="2" src="https://user-images.githubusercontent.com/24819052/37133729-10fee9d8-2263-11e8-9fac-93734e79f05b.png">
<img width="1107" alt="3" src="https://user-images.githubusercontent.com/24819052/37133735-172fc57a-2263-11e8-9007-d7cebe35c6ec.png">
failed to curl localhost and the dns for the SM instance, I also realized that as soon as I log in, it is under private IP now instead of the public IP? any advise?

**Comment by Leectan** [comment]
this is my /etc/hosts file
<img width="487" alt="4" src="https://user-images.githubusercontent.com/24819052/37133846-9d2f1b6c-2263-11e8-888b-df3136468c11.png">
