### ISSUE TITLE
Need a little clarity on add amazon accounts

### ISSUE THREAD

**Issue by devonartis** [Netflix/security_monkey#769]
The documentation states ...

add_account_aws
usage: manage.py add_account_aws [-h] -n NAME [--thirdparty] [--active]
                             [--notes NOTES] --id IDENTIFIER
                             [--update-existing]
                             [--canonical_id CANONICAL_ID]
                             [--s3_name S3_NAME] [--role_name ROLE_NAME]

Whats not really clear is  [-h] -n NAME [--thirdparty] [--active]
  [--notes NOTES] --id IDENTIFIER
  [--update-existing]
  [--canonical_id CANONICAL_ID]

The other questions would I need to create a S3 bucket and additional role name ... as the EC2 instance was already launched with the SecurityMonkeyRole .... 

Thanks for any help ...

**Comment by mikegrima** [comment]
Hello @devonartis : trying to understand what you are calling out -- are you calling out the `-n NAME` part?

> The other questions would I need to create a S3 bucket and additional role name ... as the EC2 instance was already launched with the SecurityMonkeyRole ....

You don't need to create an S3 bucket. I'm going to make an assumption that you are wondering about what the `s3_name` and `canonical_id` are referring to. These refer to how AWS references S3 principals. S3 has an older security system that relies on ACLs (bucket polices with IAM syntax were added later). The older system makes use of an ACL and this ACL has both, a friendly human readable name, and a corresponding canonical ID, which is a very long string. These refer to entire accounts. Security Monkey needs to know about these in order to determine if there is unknown or "non-friendly" cross-account access to your S3 buckets.

The S3 name is largely being ignored for new regions, and as such, the canonical ID is what really matters today. However, yours truly submitted a PR a few months ago that will automagically fetch the canonical IDs for you. There is a `monkey fetch_aws_canonical_ids` command that will do this for you (in fact, I need to update the quickstart guide to indicate this, so this is a legit gap in the docs), since the canonical ID is not easy to find. The `s3_name` is still there and useful to associate a human readable S3 ID with the canonical ID (you can see this for an S3 bucket in SM under the `GrantReferences` entry.

**Comment by mikegrima** [comment]
#770 should address documentation ambiguities.
