### ISSUE TITLE
Security Monkey POC Error Loading Page

### ISSUE THREAD

**Issue by devonartis** [Netflix/security_monkey#775]
I get this error when going to my Security Monkey Page ..

![securitymonkeyerror](https://user-images.githubusercontent.com/4836786/28597097-007350e0-716a-11e7-8b2b-178b24ec47ed.jpg)

**Comment by cplvic** [comment]
hey @devonartis I've been in the process of productionalizing SM for a bit. When I see that error it's usually because securitymonkey (nginx) is not started
do a 

sudo supervisorctl status securitymonkey
sudo supervisorctl status securitymonkeyscheduler

if it says stopped you can replace status with start and see what happens

**Comment by devonartis** [comment]
@cplvic I will try that ...

**Comment by devonartis** [comment]
Thank you .... but I then got the error securitymonkey: ERROR (spawn error)

**Comment by Xeteskian** [comment]
Have you double checked your file/directory permissions? If  serves, I had something similar when my log files weren't  set correctly.  Do a:
chown -R ubuntu:www-data /var/logs/security_monkey
and
chown -R ubuntu:www-data /usr/local/src/security_monkey
Then restart nginx and the security monkey services via supervisord

**Comment by devonartis** [comment]
I will try that ... thanks again

**Comment by cplvic** [comment]
@devonartis - I setup a new front end and I ran into your screenshot. At setup, the securitymonkey.log is not created under /var/log/security_monkey and nothing will start.
Create the file and give it the same permissions as the parent directory and see if it helps
