### ISSUE TITLE
Setup guide 

### ISSUE THREAD

**Issue by Ashishkasaudhan** [Netflix/security_monkey#892]
## Please make sure that you have checked the boxes: 

- [  ] Review the [Quickstart guide](quickstart.md)
- [ ] Search for both open and closed issues regarding the problem you are experiencing
- [x] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](iam_aws.md), [GCP](iam_gcp.md), [OpenStack](iam_openstack.md), [GitHub](github_setup.md#access-keys-and-permissions)

## Description of issue:

Hello ,
I followed the mentioned quick start instruction but i am not able to understand how to add aws account and what is the use of python virtual env also .

Can you please provide detail steps to add aws account.

**Comment by monkeysecurity** [comment]
Hey @Ashishkasaudhan ,

Let me start with the `virtualenv`.  SecurityMonkey is a python application.  Typically you want to run each python application from it's own `virtualenv` so that they can keep different dependencies and versions of dependencies.  There are different ways to use virtualenvs.

# Create a virtualenv:

    virtualenv venv

# Activate a virtualenv:

    source venv/bin/activate

# See if your virtualenv has been activated:

    which python
    # Should return the python within your `venv/bin` folder.
    # Note: activating a virtualenv only affects the shell session in which it was activated.

# virtualenvwrapper

If you end up working on a number of python projects, you can use virtualenvwrapper to organize them.    Virtualenvwrapper will put all your virtualenvs in a single folder (typically `~/.virtualenvs/`)  Wrapper comes with these methods:

    # Creates a virtualenv called securitymonkey
    mkvirtualenv securitymonkey
    
    # Shows created virtualenvs:
    lsvirtualenv

    # Activate a virtualenv
    workon securitymonkey

    # Deactrivate virtualenv
    deactivate

**Comment by monkeysecurity** [comment]
The steps to add a new AWS account are as follows:

- Create a role called `SecurityMonkey` in the new account.
- Attach the inline policy containing the permissions required.
- Edit the trust policy on the SecurityMonkey role to ensure that the SecurityMonkeyInstanceProfile in your original account is trusted.  (See the IAM docs for how to do this.)

Now login to the Security Monkey UI and go into settings.  There is a plus sign in the top right where you can add a new account.  Enter the account name, account type (AWS), the account identifier, and select `active`.  Hit Save.

At the moment we still require that you hop on the box and restart the scheduler:

`sudo supervisorctl restart securitymonkeyscheduler`
